# Generated by Django 4.0.6 on 2022-07-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='buyorrentdeal',
            name='checked',
        ),
        migrations.AddField(
            model_name='buyorrentdeal',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buyorrentdeal',
            name='status',
            field=models.CharField(choices=[('1', 'В обработке'), ('2', 'Отказ'), ('3', 'Принято')], default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='buyorrentdeal',
            name='deal_type',
            field=models.CharField(choices=[('1', 'Аренда'), ('2', 'Покупка')], max_length=10),
        ),
    ]
